server:
    port: ${PORT} # Default: 8080
    env: ${ENV} # Default: dev (options: dev, prod, staging)
    log_level: ${LOG_LEVEL} # Default: info (options: debug, info, warn, error, fatal, panic)

database:
    host: ${DB_HOST} # Default: localhost
    port: ${DB_PORT} # Default: 5432
    user: ${DB_USER} # Default: postgres
    password: ${DB_PASSWORD} # Default: your_db_password
    name: ${DB_NAME} # Default: vale-dev
    schema: ${DB_SCHEMA} # Default: public
    ssl_mode: ${DB_SSL_MODE} # Default: disable

websocket:
    ping_interval: ${WS_PING_INTERVAL} # Default: 30s
    max_message_size: ${WS_MAX_MSG_SIZE} # Default: 1024 bytes

auth:
    secret_key: ${AUTH_SECRET} # Default: supersecretkey

features:
    enable_logging: ${ENABLE_LOGGING} # Default: true
    allow_cross_origin: ${ALLOW_CORS} # Default: true
