server:
    port: ${PORT} # Default: 8080
    env: ${ENV} # Default: dev (options: dev, prod, staging)
    log_level: ${LOG_LEVEL} # Default: info (options: debug, info, warn, error, fatal, panic)

database:
    database_url: ${DATABASE_URL}

websocket:
    ping_interval: ${WS_PING_INTERVAL} # Default: 30s
    max_message_size: ${WS_MAX_MSG_SIZE} # Default: 1024 bytes

auth:
    secret_key: ${AUTH_SECRET} # Default: supersecretkey

features:
    enable_logging: ${ENABLE_LOGGING} # Default: true
    allow_cross_origin: ${ALLOW_CORS} # Default: true
